In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("50_Startups.csv")
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156991.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.95,311613.29,152211.77,0,1
9,123334.88,108679.17,304981.62,149759.96,0,0
10,101913.08,110594.11,229160.95,146121.95,1,0
11,100671.96,91790.61,249744.55,144259.40,0,0
12,93863.75,127320.38,249839.44,141585.52,1,0
13,91992.39,135495.07,252664.93,134307.35,0,0
14,119943.24,156547.42,256512.92,132602.65,1,0
15,114523.61,122616.84,261776.23,129917.04,0,1
16,78013.11,121597.55,264346.06,126992.93,0,0
17,94657.16,145077.58,282574.31,125370.37,0,1
18,91749.16,114175.79,294919.57,124266.90,1,0
19,86419.70,153514.11,0.00,122776.86,0,1
20,76253.86,113867.30,298664.47,118474.03,0,0
21,78389.47,153773.43,299737.29,111313.02,0,1
22,73994.56,122782.75,303319.26,110352.25,1,0
23,67532.53,105751.03,304768.73,108733.99,1,0
24,77044.01,99281.34,140574.81,108552.04,0,1
25,64664.71,139553.16,137962.62,107404.34,0,0
26,75328.87,144135.98,134050.07,105733.54,1,0
27,72107.60,127864.55,353183.81,105008.31,0,1
28,66051.52,182645.56,118148.20,103282.38,1,0
29,65605.48,153032.06,107138.38,101004.64,0,1
30,61994.48,115641.28,91131.24,99937.59,1,0
31,61136.38,152701.92,88218.23,97483.56,0,1
32,63408.86,129219.61,46085.25,97427.84,0,0
33,55493.95,103057.49,214634.81,96778.92,1,0
34,46426.07,157693.92,210797.67,96712.80,0,0
35,46014.02,85047.44,205517.64,96479.51,0,1
36,28663.76,127056.21,201126.82,90708.19,1,0
37,44069.95,51283.14,197029.42,89949.14,0,0
38,20229.59,65947.93,185265.10,81229.06,0,1
39,38558.51,82982.09,174999.30,81005.76,0,0
40,28754.33,118546.05,172795.67,78239.91,0,0
41,27892.92,84710.77,164470.71,77798.83,1,0
42,23640.93,96189.63,148001.11,71498.49,0,0
43,15505.73,127382.30,35534.17,69758.98,0,1
44,22177.74,154806.14,28334.72,65200.33,0,0
45,1000.23,124153.04,1903.93,64926.08,0,1
46,1315.46,115816.21,297114.46,49490.75,1,0
47,0.00,135426.92,0.00,42559.73,0,0
48,542.05,51743.15,0.00,35673.41,0,1
49,0.00,116983.80,45173.06,14681.40,0,0

In [4]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [5]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend', 'State_Florida', 'State_New York']]
independent

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.95        311613.29              0               1
9   123334.88       108679.17        304981.62              0               0
10  101913.08       110594.11        229160.95              1               0
11  100671.96        91790.61        249744.55              0               0
12   93863.75       127320.38        249839.44              1               0
13   91992.39       135495.07        252664.93              0               0
14  119943.24       156547.42        256512.92              1               0
15  114523.61       122616.84        261776.23              0               1
16   78013.11       121597.55        264346.06              0               0
17   94657.16       145077.58        282574.31              0               1
18   91749.16       114175.79        294919.57              1               0
19   86419.70       153514.11             0.00              0               1
20   76253.86       113867.30        298664.47              0               0
21   78389.47       153773.43        299737.29              0               1
22   73994.56       122782.75        303319.26              1               0
23   67532.53       105751.03        304768.73              1               0
24   77044.01        99281.34        140574.81              0               1
25   64664.71       139553.16        137962.62              0               0
26   75328.87       144135.98        134050.07              1               0
27   72107.60       127864.55        353183.81              0               1
28   66051.52       182645.56        118148.20              1               0
29   65605.48       153032.06        107138.38              0               1
30   61994.48       115641.28         91131.24              1               0
31   61136.38       152701.92         88218.23              0               1
32   63408.86       129219.61         46085.25              0               0
33   55493.95       103057.49        214634.81              1               0
34   46426.07       157693.92        210797.67              0               0
35   46014.02        85047.44        205517.64              0               1
36   28663.76       127056.21        201126.82              1               0
37   44069.95        51283.14        197029.42              0               0
38   20229.59        65947.93        185265.10              0               1
39   38558.51        82982.09        174999.30              0               0
40   28754.33       118546.05        172795.67              0               0
41   27892.92        84710.77        164470.71              1               0
42   23640.93        96189.63        148001.11              0               0
43   15505.73       127382.30         35534.17              0               1
44   22177.74       154806.14         28334.72              0               0
45    1000.23       124153.04          1903.93              0               1
46    1315.46       115816.21        297114.46              1               0
47       0.00       135426.92             0.00              0               0
48     542.05        51743.15             0.00              0               1
49       0.00       116983.80         45173.06              0               0

In [6]:
dependent=dataset[['Profit']]
dependent

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [7]:
from lightgbm import LGBMRegressor
from sklearn.model_selection import GridSearchCV

param_grid={'min_data_in_leaf':[1,3],
           'boosting_type':['dart','gbdt'],
           'objective':['regression','binary']}
grid=GridSearchCV(LGBMRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[LightGBM] [Warning] min_data_in_leaf is set=1, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=1
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=1, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=1
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000042 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 56
[LightGBM] [Info] Number of data points in the train set: 50, number of used features: 5
[LightGBM] [Info] Start training from score 112012.639102

GridSearchCV(estimator=LGBMRegressor(), n_jobs=-1,
             param_grid={'boosting_type': ['dart', 'gbdt'],
                         'min_data_in_leaf': [1, 3],
                         'objective': ['regression', 'binary']},
             verbose=3)

In [8]:
re=grid.cv_results_
print(re)

{'mean_fit_time': array([0.44664125, 0.33423223, 0.6464828 , 0.23590207, 0.32600489,
       0.31234994, 0.73027372, 0.27124429]), 'std_fit_time': array([0.23675209, 0.13616712, 0.41138684, 0.01020031, 0.13702119,
       0.09844011, 0.42316478, 0.05982911]), 'mean_score_time': array([0.01250081, 0.01249967, 0.00937557, 0.00937529, 0.0031251 ,
       0.02187719, 0.01249986, 0.01249857]), 'std_score_time': array([0.00625041, 0.00624983, 0.00765512, 0.00765489, 0.00625019,
       0.00765627, 0.00624993, 0.00624929]), 'param_boosting_type': masked_array(data=['dart', 'dart', 'dart', 'dart', 'gbdt', 'gbdt', 'gbdt',
                   'gbdt'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_min_data_in_leaf': masked_array(data=[1, 1, 3, 3, 1, 1, 3, 3],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_objective': masked_array(data=['regression', 'binary', 'regression', 'binary',
                   'regression', 'binary', 'regression', 'binary'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'boosting_type': 'dart', 'min_data_in_leaf': 1, 'objective': 'regression'}, {'boosting_type': 'dart', 'min_data_in_leaf': 1, 'objective': 'binary'}, {'boosting_type': 'dart', 'min_data_in_leaf': 3, 'objective': 'regression'}, {'boosting_type': 'dart', 'min_data_in_leaf': 3, 'objective': 'binary'}, {'boosting_type': 'gbdt', 'min_data_in_leaf': 1, 'objective': 'regression'}, {'boosting_type': 'gbdt', 'min_data_in_leaf': 1, 'objective': 'binary'}, {'boosting_type': 'gbdt', 'min_data_in_leaf': 3, 'objective': 'regression'}, {'boosting_type': 'gbdt', 'min_data_in_leaf': 3, 'objective': 'binary'}], 'split0_test_score': array([-11.79620692, -99.65621468, -10.33249605, -99.65621468,
        -7.43245414, -99.65621468,  -6.45090235, -99.65621468]), 'split1_test_score': array([  -2.28967006, -267.77559798,   -0.99612507, -267.77559798,
         -3.89521676, -267.77559798,   -0.54983636, -267.77559798]), 'split2_test_score': array([  -5.07772998, -548.25297627,   -8.77482437, -548.25297627,
         -7.02672607, -548.25297627,  -18.45915921, -548.25297627]), 'split3_test_score': array([  -9.79009008, -202.75729634,   -9.59948159, -202.75729634,
         -5.98777911, -202.75729634,   -5.18746002, -202.75729634]), 'split4_test_score': array([-1.36595639, -8.3310321 , -1.42531167, -8.3310321 , -2.76765216,
       -8.3310321 , -2.56684726, -8.3310321 ]), 'mean_test_score': array([  -6.06393068, -225.35462347,   -6.22564775, -225.35462347,
         -5.42196565, -225.35462347,   -6.64284104, -225.35462347]), 'std_test_score': array([  4.09955735, 184.10478196,   4.12646079, 184.10478196,
         1.80631155, 184.10478196,   6.25329962, 184.10478196]), 'rank_test_score': array([2, 5, 3, 5, 1, 5, 4, 5])}

In [9]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_boosting_type,param_min_data_in_leaf,param_objective,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.446641,0.236752,0.012501,0.006250,dart,1,regression,"{'boosting_type': 'dart', 'min_data_in_leaf': ...",-11.796207,-2.289670,-5.077730,-9.790090,-1.365956,-6.063931,4.099557,2
1,0.334232,0.136167,0.012500,0.006250,dart,1,binary,"{'boosting_type': 'dart', 'min_data_in_leaf': ...",-99.656215,-267.775598,-548.252976,-202.757296,-8.331032,-225.354623,184.104782,5
2,0.646483,0.411387,0.009376,0.007655,dart,3,regression,"{'boosting_type': 'dart', 'min_data_in_leaf': ...",-10.332496,-0.996125,-8.774824,-9.599482,-1.425312,-6.225648,4.126461,3
3,0.235902,0.010200,0.009375,0.007655,dart,3,binary,"{'boosting_type': 'dart', 'min_data_in_leaf': ...",-99.656215,-267.775598,-548.252976,-202.757296,-8.331032,-225.354623,184.104782,5
4,0.326005,0.137021,0.003125,0.006250,gbdt,1,regression,"{'boosting_type': 'gbdt', 'min_data_in_leaf': ...",-7.432454,-3.895217,-7.026726,-5.987779,-2.767652,-5.421966,1.806312,1
5,0.312350,0.098440,0.021877,0.007656,gbdt,1,binary,"{'boosting_type': 'gbdt', 'min_data_in_leaf': ...",-99.656215,-267.775598,-548.252976,-202.757296,-8.331032,-225.354623,184.104782,5
6,0.730274,0.423165,0.012500,0.006250,gbdt,3,regression,"{'boosting_type': 'gbdt', 'min_data_in_leaf': ...",-6.450902,-0.549836,-18.459159,-5.187460,-2.566847,-6.642841,6.253300,4
7,0.271244,0.059829,0.012499,0.006249,gbdt,3,binary,"{'boosting_type': 'gbdt', 'min_data_in_leaf': ...",-99.656215,-267.775598,-548.252976,-202.757296,-8.331032,-225.354623,184.104782,5

In [10]:
grid.best_params_

{'boosting_type': 'gbdt', 'min_data_in_leaf': 1, 'objective': 'regression'}

In [11]:
result=grid.predict([[1234,345,4565,1,0]])
result

[LightGBM] [Warning] min_data_in_leaf is set=1, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=1

array([35675.57711428])