In [1]:
#import pandas
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
train_independent=sc.fit_transform(independent)

In [8]:
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV

param_grid={'kernel':['linear','rbf','poly'],
           'gamma':['scale','auto'],
           'C':[5,10]}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(train_independent,dependent)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [5, 10], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf', 'poly']},
             verbose=3)

In [9]:
re=grid.cv_results_
print(re)

{'mean_fit_time': array([0.18817329, 0.21530399, 0.17192259, 0.17434607, 0.18341942,
       0.13999257, 0.22481985, 0.22363706, 0.17518454, 0.18527303,
       0.21881862, 0.16528692]), 'std_fit_time': array([1.26629022e-02, 1.16212073e-02, 7.32775692e-05, 5.56025472e-03,
       2.26273778e-02, 7.88098123e-04, 3.52028801e-02, 1.37307212e-02,
       6.12535083e-03, 1.17940576e-02, 9.96114622e-03, 7.39878529e-03]), 'mean_score_time': array([0.02981024, 0.09033341, 0.02900424, 0.03125377, 0.06875491,
       0.02187629, 0.02812719, 0.0947072 , 0.02500076, 0.0265831 ,
       0.09345479, 0.03382401]), 'std_score_time': array([7.80582572e-03, 1.11753903e-02, 6.90008653e-03, 9.70220087e-07,
       7.65560935e-03, 7.65564855e-03, 6.25050076e-03, 1.90165070e-03,
       7.65595974e-03, 6.24082083e-03, 9.98784996e-03, 5.14159224e-03]), 'param_C': masked_array(data=[5, 5, 5, 5, 5, 5, 10, 10, 10, 10, 10, 10],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'param_gamma': masked_array(data=['scale', 'scale', 'scale', 'auto', 'auto', 'auto',
                   'scale', 'scale', 'scale', 'auto', 'auto', 'auto'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'param_kernel': masked_array(data=['linear', 'rbf', 'poly', 'linear', 'rbf', 'poly',
                   'linear', 'rbf', 'poly', 'linear', 'rbf', 'poly'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'C': 5, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 5, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 5, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 5, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 5, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 5, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 10, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}], 'split0_test_score': array([ 0.26091646, -0.08232036, -0.03652487,  0.26091646, -0.08226976,
       -0.03754397,  0.48787341, -0.05051686,  0.03904118,  0.48787341,
       -0.0504021 ,  0.03722664]), 'split1_test_score': array([ 0.27761422, -0.07747139, -0.03177619,  0.27761422, -0.07757036,
       -0.03024398,  0.47234116, -0.04509649,  0.04011056,  0.47234116,
       -0.04527595,  0.04288373]), 'split2_test_score': array([ 0.28723596, -0.04903581, -0.00596775,  0.28723596, -0.04911292,
       -0.00470727,  0.48510241, -0.01660105,  0.06336243,  0.48510241,
       -0.01673688,  0.06567166]), 'split3_test_score': array([ 0.26682999, -0.07519124, -0.03069286,  0.26682999, -0.07515719,
       -0.03129181,  0.47583469, -0.04141474,  0.04250578,  0.47583469,
       -0.04134517,  0.04140573]), 'split4_test_score': array([ 0.22538746, -0.07687669, -0.03498445,  0.22538746, -0.07682358,
       -0.03613961,  0.44769233, -0.0486001 ,  0.03659431,  0.44769233,
       -0.04849124,  0.03439333]), 'mean_test_score': array([ 0.26359682, -0.0721791 , -0.02798923,  0.26359682, -0.07218676,
       -0.02798533,  0.4737688 , -0.04044585,  0.04432285,  0.4737688 ,
       -0.04045027,  0.04431622]), 'std_test_score': array([0.02113239, 0.01181191, 0.01121059, 0.02113239, 0.01177604,
       0.01196463, 0.01423853, 0.01232119, 0.00970749, 0.01423853,
       0.01224834, 0.01109328]), 'rank_test_score': array([ 3, 11,  8,  3, 12,  7,  1,  9,  5,  1, 10,  6])}

In [10]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.188173,0.012663,0.029810,7.805826e-03,5,scale,linear,"{'C': 5, 'gamma': 'scale', 'kernel': 'linear'}",0.260916,0.277614,0.287236,0.266830,0.225387,0.263597,0.021132,3
1,0.215304,0.011621,0.090333,1.117539e-02,5,scale,rbf,"{'C': 5, 'gamma': 'scale', 'kernel': 'rbf'}",-0.082320,-0.077471,-0.049036,-0.075191,-0.076877,-0.072179,0.011812,11
2,0.171923,0.000073,0.029004,6.900087e-03,5,scale,poly,"{'C': 5, 'gamma': 'scale', 'kernel': 'poly'}",-0.036525,-0.031776,-0.005968,-0.030693,-0.034984,-0.027989,0.011211,8
3,0.174346,0.005560,0.031254,9.702201e-07,5,auto,linear,"{'C': 5, 'gamma': 'auto', 'kernel': 'linear'}",0.260916,0.277614,0.287236,0.266830,0.225387,0.263597,0.021132,3
4,0.183419,0.022627,0.068755,7.655609e-03,5,auto,rbf,"{'C': 5, 'gamma': 'auto', 'kernel': 'rbf'}",-0.082270,-0.077570,-0.049113,-0.075157,-0.076824,-0.072187,0.011776,12
5,0.139993,0.000788,0.021876,7.655649e-03,5,auto,poly,"{'C': 5, 'gamma': 'auto', 'kernel': 'poly'}",-0.037544,-0.030244,-0.004707,-0.031292,-0.036140,-0.027985,0.011965,7
6,0.224820,0.035203,0.028127,6.250501e-03,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.487873,0.472341,0.485102,0.475835,0.447692,0.473769,0.014239,1
7,0.223637,0.013731,0.094707,1.901651e-03,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.050517,-0.045096,-0.016601,-0.041415,-0.048600,-0.040446,0.012321,9
8,0.175185,0.006125,0.025001,7.655960e-03,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.039041,0.040111,0.063362,0.042506,0.036594,0.044323,0.009707,5
9,0.185273,0.011794,0.026583,6.240821e-03,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.487873,0.472341,0.485102,0.475835,0.447692,0.473769,0.014239,1
10,0.218819,0.009961,0.093455,9.987850e-03,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.050402,-0.045276,-0.016737,-0.041345,-0.048491,-0.040450,0.012248,10
11,0.165287,0.007399,0.033824,5.141592e-03,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.037227,0.042884,0.065672,0.041406,0.034393,0.044316,0.011093,6

In [11]:
grid.best_params_

{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}

In [12]:
Y_predict=grid.predict(train_independent)
Y_predict

array([14634.6122649 ,  1802.28041261,  5068.65623786, ...,
        1792.567662  ,  2355.15394815, 25007.83401461])

In [13]:
from sklearn.metrics import r2_score
r2=r2_score(dependent,Y_predict)
r2

0.5055772867405952

In [14]:
preinput=sc.transform([[40,28.5,2,1,0]])
result=grid.predict(preinput)
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([7548.30981815])