In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("50_Startups.csv")
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156991.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.95,311613.29,152211.77,0,1
9,123334.88,108679.17,304981.62,149759.96,0,0
10,101913.08,110594.11,229160.95,146121.95,1,0
11,100671.96,91790.61,249744.55,144259.40,0,0
12,93863.75,127320.38,249839.44,141585.52,1,0
13,91992.39,135495.07,252664.93,134307.35,0,0
14,119943.24,156547.42,256512.92,132602.65,1,0
15,114523.61,122616.84,261776.23,129917.04,0,1
16,78013.11,121597.55,264346.06,126992.93,0,0
17,94657.16,145077.58,282574.31,125370.37,0,1
18,91749.16,114175.79,294919.57,124266.90,1,0
19,86419.70,153514.11,0.00,122776.86,0,1
20,76253.86,113867.30,298664.47,118474.03,0,0
21,78389.47,153773.43,299737.29,111313.02,0,1
22,73994.56,122782.75,303319.26,110352.25,1,0
23,67532.53,105751.03,304768.73,108733.99,1,0
24,77044.01,99281.34,140574.81,108552.04,0,1
25,64664.71,139553.16,137962.62,107404.34,0,0
26,75328.87,144135.98,134050.07,105733.54,1,0
27,72107.60,127864.55,353183.81,105008.31,0,1
28,66051.52,182645.56,118148.20,103282.38,1,0
29,65605.48,153032.06,107138.38,101004.64,0,1
30,61994.48,115641.28,91131.24,99937.59,1,0
31,61136.38,152701.92,88218.23,97483.56,0,1
32,63408.86,129219.61,46085.25,97427.84,0,0
33,55493.95,103057.49,214634.81,96778.92,1,0
34,46426.07,157693.92,210797.67,96712.80,0,0
35,46014.02,85047.44,205517.64,96479.51,0,1
36,28663.76,127056.21,201126.82,90708.19,1,0
37,44069.95,51283.14,197029.42,89949.14,0,0
38,20229.59,65947.93,185265.10,81229.06,0,1
39,38558.51,82982.09,174999.30,81005.76,0,0
40,28754.33,118546.05,172795.67,78239.91,0,0
41,27892.92,84710.77,164470.71,77798.83,1,0
42,23640.93,96189.63,148001.11,71498.49,0,0
43,15505.73,127382.30,35534.17,69758.98,0,1
44,22177.74,154806.14,28334.72,65200.33,0,0
45,1000.23,124153.04,1903.93,64926.08,0,1
46,1315.46,115816.21,297114.46,49490.75,1,0
47,0.00,135426.92,0.00,42559.73,0,0
48,542.05,51743.15,0.00,35673.41,0,1
49,0.00,116983.80,45173.06,14681.40,0,0

In [4]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [5]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend', 'State_Florida', 'State_New York']]
independent

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.95        311613.29              0               1
9   123334.88       108679.17        304981.62              0               0
10  101913.08       110594.11        229160.95              1               0
11  100671.96        91790.61        249744.55              0               0
12   93863.75       127320.38        249839.44              1               0
13   91992.39       135495.07        252664.93              0               0
14  119943.24       156547.42        256512.92              1               0
15  114523.61       122616.84        261776.23              0               1
16   78013.11       121597.55        264346.06              0               0
17   94657.16       145077.58        282574.31              0               1
18   91749.16       114175.79        294919.57              1               0
19   86419.70       153514.11             0.00              0               1
20   76253.86       113867.30        298664.47              0               0
21   78389.47       153773.43        299737.29              0               1
22   73994.56       122782.75        303319.26              1               0
23   67532.53       105751.03        304768.73              1               0
24   77044.01        99281.34        140574.81              0               1
25   64664.71       139553.16        137962.62              0               0
26   75328.87       144135.98        134050.07              1               0
27   72107.60       127864.55        353183.81              0               1
28   66051.52       182645.56        118148.20              1               0
29   65605.48       153032.06        107138.38              0               1
30   61994.48       115641.28         91131.24              1               0
31   61136.38       152701.92         88218.23              0               1
32   63408.86       129219.61         46085.25              0               0
33   55493.95       103057.49        214634.81              1               0
34   46426.07       157693.92        210797.67              0               0
35   46014.02        85047.44        205517.64              0               1
36   28663.76       127056.21        201126.82              1               0
37   44069.95        51283.14        197029.42              0               0
38   20229.59        65947.93        185265.10              0               1
39   38558.51        82982.09        174999.30              0               0
40   28754.33       118546.05        172795.67              0               0
41   27892.92        84710.77        164470.71              1               0
42   23640.93        96189.63        148001.11              0               0
43   15505.73       127382.30         35534.17              0               1
44   22177.74       154806.14         28334.72              0               0
45    1000.23       124153.04          1903.93              0               1
46    1315.46       115816.21        297114.46              1               0
47       0.00       135426.92             0.00              0               0
48     542.05        51743.15             0.00              0               1
49       0.00       116983.80         45173.06              0               0

In [6]:
dependent=dataset[['Profit']]
dependent

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [8]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV

param_grid={'objective':['reg:squarederror','reg:linear'],
           'seed':[100,500],
           'n_estimators':[100,50]}
grid=GridSearchCV(XGBRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, gamma=None,
                                    grow_policy=None, importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, max_bi...
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None,
                                    random_state=None, ...),
             n_jobs=-1,
             param_grid={'n_estimators': [100, 50],
                         'objective': ['reg:squarederror', 'reg:linear'],
                         'seed': [100, 500]},
             verbose=3)

In [9]:
re=grid.cv_results_
print(re)

{'mean_fit_time': array([0.13994803, 0.12271905, 0.16502333, 0.12501321, 0.08406096,
       0.07813063, 0.09562984, 0.08961601]), 'std_fit_time': array([0.02580931, 0.00685894, 0.04391882, 0.00988189, 0.00721845,
       0.00988461, 0.01150431, 0.00607113]), 'mean_score_time': array([0.02187605, 0.01673322, 0.00937386, 0.01874962, 0.01954637,
       0.01874757, 0.0156281 , 0.02075644]), 'std_score_time': array([7.65632992e-03, 1.01275778e-02, 7.65372133e-03, 6.25054908e-03,
       7.84606950e-03, 6.25074112e-03, 2.36983750e-06, 6.52797631e-03]), 'param_n_estimators': masked_array(data=[100, 100, 100, 100, 50, 50, 50, 50],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_objective': masked_array(data=['reg:squarederror', 'reg:squarederror', 'reg:linear',
                   'reg:linear', 'reg:squarederror', 'reg:squarederror',
                   'reg:linear', 'reg:linear'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_seed': masked_array(data=[100, 500, 100, 500, 100, 500, 100, 500],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'n_estimators': 100, 'objective': 'reg:squarederror', 'seed': 100}, {'n_estimators': 100, 'objective': 'reg:squarederror', 'seed': 500}, {'n_estimators': 100, 'objective': 'reg:linear', 'seed': 100}, {'n_estimators': 100, 'objective': 'reg:linear', 'seed': 500}, {'n_estimators': 50, 'objective': 'reg:squarederror', 'seed': 100}, {'n_estimators': 50, 'objective': 'reg:squarederror', 'seed': 500}, {'n_estimators': 50, 'objective': 'reg:linear', 'seed': 100}, {'n_estimators': 50, 'objective': 'reg:linear', 'seed': 500}], 'split0_test_score': array([-7.79533854, -7.79533854, -7.79533854, -7.79533854, -7.79529853,
       -7.79529853, -7.79529853, -7.79529853]), 'split1_test_score': array([-6.69668907, -6.69668907, -6.69668907, -6.69668907, -6.69969244,
       -6.69969244, -6.69969244, -6.69969244]), 'split2_test_score': array([-4.08203537, -4.08203537, -4.08203537, -4.08203537, -4.08205639,
       -4.08205639, -4.08205639, -4.08205639]), 'split3_test_score': array([-5.49733543, -5.49733543, -5.49733543, -5.49733543, -5.49622404,
       -5.49622404, -5.49622404, -5.49622404]), 'split4_test_score': array([-2.76900977, -2.76900977, -2.76900977, -2.76900977, -2.76925145,
       -2.76925145, -2.76925145, -2.76925145]), 'mean_test_score': array([-5.36808164, -5.36808164, -5.36808164, -5.36808164, -5.36850457,
       -5.36850457, -5.36850457, -5.36850457]), 'std_test_score': array([1.79346424, 1.79346424, 1.79346424, 1.79346424, 1.7938098 ,
       1.7938098 , 1.7938098 , 1.7938098 ]), 'rank_test_score': array([1, 1, 1, 1, 5, 5, 5, 5])}

In [10]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_estimators,param_objective,param_seed,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.139948,0.025809,0.021876,0.007656,100,reg:squarederror,100,"{'n_estimators': 100, 'objective': 'reg:square...",-7.795339,-6.696689,-4.082035,-5.497335,-2.769010,-5.368082,1.793464,1
1,0.122719,0.006859,0.016733,0.010128,100,reg:squarederror,500,"{'n_estimators': 100, 'objective': 'reg:square...",-7.795339,-6.696689,-4.082035,-5.497335,-2.769010,-5.368082,1.793464,1
2,0.165023,0.043919,0.009374,0.007654,100,reg:linear,100,"{'n_estimators': 100, 'objective': 'reg:linear...",-7.795339,-6.696689,-4.082035,-5.497335,-2.769010,-5.368082,1.793464,1
3,0.125013,0.009882,0.018750,0.006251,100,reg:linear,500,"{'n_estimators': 100, 'objective': 'reg:linear...",-7.795339,-6.696689,-4.082035,-5.497335,-2.769010,-5.368082,1.793464,1
4,0.084061,0.007218,0.019546,0.007846,50,reg:squarederror,100,"{'n_estimators': 50, 'objective': 'reg:squared...",-7.795299,-6.699692,-4.082056,-5.496224,-2.769251,-5.368505,1.793810,5
5,0.078131,0.009885,0.018748,0.006251,50,reg:squarederror,500,"{'n_estimators': 50, 'objective': 'reg:squared...",-7.795299,-6.699692,-4.082056,-5.496224,-2.769251,-5.368505,1.793810,5
6,0.095630,0.011504,0.015628,0.000002,50,reg:linear,100,"{'n_estimators': 50, 'objective': 'reg:linear'...",-7.795299,-6.699692,-4.082056,-5.496224,-2.769251,-5.368505,1.793810,5
7,0.089616,0.006071,0.020756,0.006528,50,reg:linear,500,"{'n_estimators': 50, 'objective': 'reg:linear'...",-7.795299,-6.699692,-4.082056,-5.496224,-2.769251,-5.368505,1.793810,5

In [11]:
grid.best_params_

{'n_estimators': 100, 'objective': 'reg:squarederror', 'seed': 100}

In [12]:
result=grid.predict([[1234,345,4565,1,0]])
result

array([54290.52], dtype=float32)